model:
  which_model_G: sr3  # use the ddpm or sr3 network structure
  finetune_norm: false
  unet:
    in_channel: 2
    out_channel: 1
    inner_channel: 64
    norm_groups: 16
    channel_multiplier:
      - 1
      - 2
      - 4
      - 8
      - 8
    attn_res:
      - 16
    res_blocks: 2
    dropout: 0.2
  beta_schedule:  # use manual beta_schedule for acceleration
    train:
      schedule: linear
      n_timestep: 2000
      linear_start: 1e-6
      linear_end: 1e-2
    val:
      schedule: linear
      n_timestep: 2000
      linear_start: 1e-6
      linear_end: 1e-2
  diffusion:
    image_size: 128
    channels: 1  # sample channel
    conditional: true  # unconditional generation or unconditional generation(super_resolution)
    num_diffusion_timesteps: 2000
